/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as FilesRouteImport } from './routes/files'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as TaskGidRouteImport } from './routes/task.$gid'
import { Route as SettingsRemotesRouteImport } from './routes/settings.remotes'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsEngineRouteImport } from './routes/settings.engine'
import { Route as SettingsConnectionRouteImport } from './routes/settings.connection'
import { Route as SettingsAppRouteImport } from './routes/settings.app'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskGidRoute = TaskGidRouteImport.update({
  id: '/task/$gid',
  path: '/task/$gid',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRemotesRoute = SettingsRemotesRouteImport.update({
  id: '/settings/remotes',
  path: '/settings/remotes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/settings/providers',
  path: '/settings/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEngineRoute = SettingsEngineRouteImport.update({
  id: '/settings/engine',
  path: '/settings/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionRoute = SettingsConnectionRouteImport.update({
  id: '/settings/connection',
  path: '/settings/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppRoute = SettingsAppRouteImport.update({
  id: '/settings/app',
  path: '/settings/app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/files': typeof FilesRoute
  '/tasks': typeof TasksRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/engine': typeof SettingsEngineRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/remotes': typeof SettingsRemotesRoute
  '/task/$gid': typeof TaskGidRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/files': typeof FilesRoute
  '/tasks': typeof TasksRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/engine': typeof SettingsEngineRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/remotes': typeof SettingsRemotesRoute
  '/task/$gid': typeof TaskGidRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/files': typeof FilesRoute
  '/tasks': typeof TasksRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/engine': typeof SettingsEngineRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/remotes': typeof SettingsRemotesRoute
  '/task/$gid': typeof TaskGidRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/files'
    | '/tasks'
    | '/settings/app'
    | '/settings/connection'
    | '/settings/engine'
    | '/settings/providers'
    | '/settings/remotes'
    | '/task/$gid'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/files'
    | '/tasks'
    | '/settings/app'
    | '/settings/connection'
    | '/settings/engine'
    | '/settings/providers'
    | '/settings/remotes'
    | '/task/$gid'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/files'
    | '/tasks'
    | '/settings/app'
    | '/settings/connection'
    | '/settings/engine'
    | '/settings/providers'
    | '/settings/remotes'
    | '/task/$gid'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  FilesRoute: typeof FilesRoute
  TasksRoute: typeof TasksRoute
  SettingsAppRoute: typeof SettingsAppRoute
  SettingsConnectionRoute: typeof SettingsConnectionRoute
  SettingsEngineRoute: typeof SettingsEngineRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsRemotesRoute: typeof SettingsRemotesRoute
  TaskGidRoute: typeof TaskGidRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$gid': {
      id: '/task/$gid'
      path: '/task/$gid'
      fullPath: '/task/$gid'
      preLoaderRoute: typeof TaskGidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/remotes': {
      id: '/settings/remotes'
      path: '/settings/remotes'
      fullPath: '/settings/remotes'
      preLoaderRoute: typeof SettingsRemotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/engine': {
      id: '/settings/engine'
      path: '/settings/engine'
      fullPath: '/settings/engine'
      preLoaderRoute: typeof SettingsEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/connection': {
      id: '/settings/connection'
      path: '/settings/connection'
      fullPath: '/settings/connection'
      preLoaderRoute: typeof SettingsConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/app': {
      id: '/settings/app'
      path: '/settings/app'
      fullPath: '/settings/app'
      preLoaderRoute: typeof SettingsAppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  FilesRoute: FilesRoute,
  TasksRoute: TasksRoute,
  SettingsAppRoute: SettingsAppRoute,
  SettingsConnectionRoute: SettingsConnectionRoute,
  SettingsEngineRoute: SettingsEngineRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsRemotesRoute: SettingsRemotesRoute,
  TaskGidRoute: TaskGidRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
