/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as FilesRouteImport } from './routes/files'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as TaskGidRouteImport } from './routes/task.$gid'
import { Route as SettingsTorrentsRouteImport } from './routes/settings.torrents'
import { Route as SettingsPremiumRouteImport } from './routes/settings.premium'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsNetworkRouteImport } from './routes/settings.network'
import { Route as SettingsDownloadsRouteImport } from './routes/settings.downloads'
import { Route as SettingsCloudRouteImport } from './routes/settings.cloud'
import { Route as SettingsBrowserRouteImport } from './routes/settings.browser'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskGidRoute = TaskGidRouteImport.update({
  id: '/task/$gid',
  path: '/task/$gid',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTorrentsRoute = SettingsTorrentsRouteImport.update({
  id: '/settings/torrents',
  path: '/settings/torrents',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPremiumRoute = SettingsPremiumRouteImport.update({
  id: '/settings/premium',
  path: '/settings/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNetworkRoute = SettingsNetworkRouteImport.update({
  id: '/settings/network',
  path: '/settings/network',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDownloadsRoute = SettingsDownloadsRouteImport.update({
  id: '/settings/downloads',
  path: '/settings/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCloudRoute = SettingsCloudRouteImport.update({
  id: '/settings/cloud',
  path: '/settings/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBrowserRoute = SettingsBrowserRouteImport.update({
  id: '/settings/browser',
  path: '/settings/browser',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/files': typeof FilesRoute
  '/tasks': typeof TasksRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/cloud': typeof SettingsCloudRoute
  '/settings/downloads': typeof SettingsDownloadsRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/premium': typeof SettingsPremiumRoute
  '/settings/torrents': typeof SettingsTorrentsRoute
  '/task/$gid': typeof TaskGidRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/files': typeof FilesRoute
  '/tasks': typeof TasksRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/cloud': typeof SettingsCloudRoute
  '/settings/downloads': typeof SettingsDownloadsRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/premium': typeof SettingsPremiumRoute
  '/settings/torrents': typeof SettingsTorrentsRoute
  '/task/$gid': typeof TaskGidRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/files': typeof FilesRoute
  '/tasks': typeof TasksRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/cloud': typeof SettingsCloudRoute
  '/settings/downloads': typeof SettingsDownloadsRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/premium': typeof SettingsPremiumRoute
  '/settings/torrents': typeof SettingsTorrentsRoute
  '/task/$gid': typeof TaskGidRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/files'
    | '/tasks'
    | '/settings/browser'
    | '/settings/cloud'
    | '/settings/downloads'
    | '/settings/network'
    | '/settings/preferences'
    | '/settings/premium'
    | '/settings/torrents'
    | '/task/$gid'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/files'
    | '/tasks'
    | '/settings/browser'
    | '/settings/cloud'
    | '/settings/downloads'
    | '/settings/network'
    | '/settings/preferences'
    | '/settings/premium'
    | '/settings/torrents'
    | '/task/$gid'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/files'
    | '/tasks'
    | '/settings/browser'
    | '/settings/cloud'
    | '/settings/downloads'
    | '/settings/network'
    | '/settings/preferences'
    | '/settings/premium'
    | '/settings/torrents'
    | '/task/$gid'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  FilesRoute: typeof FilesRoute
  TasksRoute: typeof TasksRoute
  SettingsBrowserRoute: typeof SettingsBrowserRoute
  SettingsCloudRoute: typeof SettingsCloudRoute
  SettingsDownloadsRoute: typeof SettingsDownloadsRoute
  SettingsNetworkRoute: typeof SettingsNetworkRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsPremiumRoute: typeof SettingsPremiumRoute
  SettingsTorrentsRoute: typeof SettingsTorrentsRoute
  TaskGidRoute: typeof TaskGidRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$gid': {
      id: '/task/$gid'
      path: '/task/$gid'
      fullPath: '/task/$gid'
      preLoaderRoute: typeof TaskGidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/torrents': {
      id: '/settings/torrents'
      path: '/settings/torrents'
      fullPath: '/settings/torrents'
      preLoaderRoute: typeof SettingsTorrentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/premium': {
      id: '/settings/premium'
      path: '/settings/premium'
      fullPath: '/settings/premium'
      preLoaderRoute: typeof SettingsPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/network': {
      id: '/settings/network'
      path: '/settings/network'
      fullPath: '/settings/network'
      preLoaderRoute: typeof SettingsNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/downloads': {
      id: '/settings/downloads'
      path: '/settings/downloads'
      fullPath: '/settings/downloads'
      preLoaderRoute: typeof SettingsDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/cloud': {
      id: '/settings/cloud'
      path: '/settings/cloud'
      fullPath: '/settings/cloud'
      preLoaderRoute: typeof SettingsCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/browser': {
      id: '/settings/browser'
      path: '/settings/browser'
      fullPath: '/settings/browser'
      preLoaderRoute: typeof SettingsBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  FilesRoute: FilesRoute,
  TasksRoute: TasksRoute,
  SettingsBrowserRoute: SettingsBrowserRoute,
  SettingsCloudRoute: SettingsCloudRoute,
  SettingsDownloadsRoute: SettingsDownloadsRoute,
  SettingsNetworkRoute: SettingsNetworkRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsPremiumRoute: SettingsPremiumRoute,
  SettingsTorrentsRoute: SettingsTorrentsRoute,
  TaskGidRoute: TaskGidRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
