/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksWaitingRouteImport } from './routes/tasks.waiting'
import { Route as TasksStoppedRouteImport } from './routes/tasks.stopped'
import { Route as TasksAllRouteImport } from './routes/tasks.all'
import { Route as TasksActiveRouteImport } from './routes/tasks.active'
import { Route as TaskGidRouteImport } from './routes/task.$gid'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksWaitingRoute = TasksWaitingRouteImport.update({
  id: '/tasks/waiting',
  path: '/tasks/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksStoppedRoute = TasksStoppedRouteImport.update({
  id: '/tasks/stopped',
  path: '/tasks/stopped',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksAllRoute = TasksAllRouteImport.update({
  id: '/tasks/all',
  path: '/tasks/all',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksActiveRoute = TasksActiveRouteImport.update({
  id: '/tasks/active',
  path: '/tasks/active',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskGidRoute = TaskGidRouteImport.update({
  id: '/task/$gid',
  path: '/task/$gid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/settings': typeof SettingsRoute
  '/task/$gid': typeof TaskGidRoute
  '/tasks/active': typeof TasksActiveRoute
  '/tasks/all': typeof TasksAllRoute
  '/tasks/stopped': typeof TasksStoppedRoute
  '/tasks/waiting': typeof TasksWaitingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/settings': typeof SettingsRoute
  '/task/$gid': typeof TaskGidRoute
  '/tasks/active': typeof TasksActiveRoute
  '/tasks/all': typeof TasksAllRoute
  '/tasks/stopped': typeof TasksStoppedRoute
  '/tasks/waiting': typeof TasksWaitingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/settings': typeof SettingsRoute
  '/task/$gid': typeof TaskGidRoute
  '/tasks/active': typeof TasksActiveRoute
  '/tasks/all': typeof TasksAllRoute
  '/tasks/stopped': typeof TasksStoppedRoute
  '/tasks/waiting': typeof TasksWaitingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/settings'
    | '/task/$gid'
    | '/tasks/active'
    | '/tasks/all'
    | '/tasks/stopped'
    | '/tasks/waiting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/settings'
    | '/task/$gid'
    | '/tasks/active'
    | '/tasks/all'
    | '/tasks/stopped'
    | '/tasks/waiting'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/settings'
    | '/task/$gid'
    | '/tasks/active'
    | '/tasks/all'
    | '/tasks/stopped'
    | '/tasks/waiting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  SettingsRoute: typeof SettingsRoute
  TaskGidRoute: typeof TaskGidRoute
  TasksActiveRoute: typeof TasksActiveRoute
  TasksAllRoute: typeof TasksAllRoute
  TasksStoppedRoute: typeof TasksStoppedRoute
  TasksWaitingRoute: typeof TasksWaitingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/waiting': {
      id: '/tasks/waiting'
      path: '/tasks/waiting'
      fullPath: '/tasks/waiting'
      preLoaderRoute: typeof TasksWaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/stopped': {
      id: '/tasks/stopped'
      path: '/tasks/stopped'
      fullPath: '/tasks/stopped'
      preLoaderRoute: typeof TasksStoppedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/all': {
      id: '/tasks/all'
      path: '/tasks/all'
      fullPath: '/tasks/all'
      preLoaderRoute: typeof TasksAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/active': {
      id: '/tasks/active'
      path: '/tasks/active'
      fullPath: '/tasks/active'
      preLoaderRoute: typeof TasksActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$gid': {
      id: '/task/$gid'
      path: '/task/$gid'
      fullPath: '/task/$gid'
      preLoaderRoute: typeof TaskGidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  SettingsRoute: SettingsRoute,
  TaskGidRoute: TaskGidRoute,
  TasksActiveRoute: TasksActiveRoute,
  TasksAllRoute: TasksAllRoute,
  TasksStoppedRoute: TasksStoppedRoute,
  TasksWaitingRoute: TasksWaitingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
